### ISSUE TITLE
switch from pure char codes to delimited hex

### ISSUE THREAD

**Issue by Semisol** [InternationalScratchWiki/scratch-confirmaccount-v3#114]
The current approach might create swear words or unwantedly get some codes blocked, while pure hex may trip the phone censors. Instead, I recommend switching to delimited hex (like the old system, but change to using `-` as punctuation and punctuate every 4 chars)

**Comment by jacob-g** [comment]
So on CA2, we had to use commas because of a different issue: the phone filter, which blocked any string of 10 digits (even separated by hyphens, since you could write something like 1-800-555-0000), which is why it used commas. So if we do institute character separation, we should use commas.

**Comment by Semisol** [comment]
> So on CA2, we had to use commas because of a different issue: the phone filter, which blocked any string of 10 digits (even separated by hyphens, since you could write something like 1-800-555-0000), which is why it used commas. So if we do institute character separation, we should use commas.

/es look neater IMO and they seem to work.

**Comment by jacob-g** [comment]
Ok, as long as it doesn't trip the phone filter, that should be fine.

**Comment by Semisol** [comment]
Hopefully. One moment

**Comment by Kenny2github** [comment]
What about colons?

**Comment by jacob-g** [comment]
![image](https://user-images.githubusercontent.com/1960707/113438625-8cc14100-93ae-11eb-80f1-fd65a61c3a8e.png)
Colons seem to work also.

**Comment by jacob-g** [comment]
![image](https://user-images.githubusercontent.com/1960707/113438656-9cd92080-93ae-11eb-91e4-749a4366d73c.png)
Slashes also appear to work.

**Comment by Semisol** [comment]
![image](https://user-images.githubusercontent.com/45574030/113438682-bcde0380-93f1-11eb-9c97-dd910a0235b8.png)

**Comment by Semisol** [comment]
![image](https://user-images.githubusercontent.com/45574030/113438719-d3845a80-93f1-11eb-9d9b-f05cf3fae3e6.png)
These did not trip, but there might be edge cases.
