### ISSUE TITLE
French Translation Error

### ISSUE THREAD

**Issue by happexx** [InternationalScratchWiki/scratch-confirmaccount-v3#156]
![EE1FD0BE-B4CB-4FE8-AC4B-4FF7E3823172](https://user-images.githubusercontent.com/79383503/148108484-9a98d403-707f-4e71-aa18-cc25f003b7ff.jpeg)

https://github.com/InternationalScratchWiki/scratch-confirmaccount-v3/blob/master/src/ScratchConfirmAccount.i18n.alias.php

"Dem**en**derUnCompte" should be writed like that "Dem**an**derUnCompte"

**Comment by jacob-g** [comment]
Done in PR #157 - please look to make sure I did it right
