### ISSUE TITLE
PersonalUrls deprecated in 1.39

### ISSUE THREAD

**Issue by jdlrobson** [InternationalScratchWiki/scratch-confirmaccount-v3#166]
Hi there!
Just a friendly notification that we've deprecated a hook being used by this codebase in 1.39 and hope to remove it by 1.41.

Details on how to migrate can be found here https://phabricator.wikimedia.org/T319087
If you don't support MediaWiki 1.39 feel free to disregard this message until you do.

**Comment by apple502j** [comment]
@jdlrobson We do intend to support 1.39, however we currently use 1.35LTS in production. Is the hook still compatible with 1.35? I heard from somewhere it's 1.36+ only.

**Comment by jdlrobson** [comment]
Yeh it's 1.36 only. You could perhaps use version_compare to conditionally register the hook if you wanted to get a head start on addressing this and didn't want to wait.
