### ISSUE TITLE
Hooks are not firing in latest update

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/scratch-confirmaccount-v3#172]
After the upgrade to fix deprecations and prepare for MW 1.39, the webhooks stopped firing. This most likely means they aren't being invoked correctly.

**Comment by apple502j** [comment]
@jacob-g Are you sure the hook users are using the nee HookHandler system? Also hooks were renamed (and noted as a breaking change in the PR). The code correctly fires hooks with MW1.35 on PHP7.4 using HookHandler system.

As this is not an issue with this repository's code, I am closing this.
