### ISSUE TITLE
Don't Mark Creation Of User Talk Page As Minor

### ISSUE THREAD

**Issue by mrsrec** [InternationalScratchWiki/scratch-confirmaccount-v3#190]
In MediaWiki, Users Cannot Mark The Creation Of A Page As Minor, Nor Should They Be Able To. Currently, The Confirm Account's Automated Welcome Is Marking The Creation Of A User As Minor, Which Should Not Be Happening.

**Comment by jacob-g** [comment]
Please use proper capitalization. We will not review the issue until you fix it.
