### ISSUE TITLE
User count not incremented on account creation

### ISSUE THREAD

**Issue by Mrcomputer1** [InternationalScratchWiki/scratch-confirmaccount-v3#197]
[User:Purin2022](https://en.scratch-wiki.info/wiki/User:Purin2022) noticed ([here](https://en.scratch-wiki.info/wiki/User:Purin2022/List_of_All_Users_on_the_Scratch_Wiki) and [here](https://en.scratch-wiki.info/w/index.php?redirect=no&title=User%20talk%3APurin2022%2FList_of_All_Users_on_the_Scratch_Wiki)) that the `{{NUMBEROFUSERS}}` magic word reports that there are 2379 registered users, while [Special:ListUsers](https://en.scratch-wiki.info/wiki/Special:ListUsers) lists 3682+ users, which is over 1000 additional users.

The `{{NUMBEROFUSERS}}` (and also the [Special:Statistics](https://en.scratch-wiki.info/wiki/Special:Statistics) special page) retrieves the user count from the [`site_stats`](https://www.mediawiki.org/wiki/Manual:Site_stats_table) table's `ss_users` field. In MediaWiki's `AuthManager`, after creating the user, this stat is incremented [here](https://github.com/wikimedia/mediawiki/blob/fa9796657ed7413b80aa7b033a6de86473b7ed18/includes/auth/AuthManager.php#L1653-L1654) with this code:
```php
// Update user count
DeferredUpdates::addUpdate( SiteStatsUpdate::factory( [ 'users' => 1 ] ) );
```
When creating an account, Scratch ConfirmAccount does not increment that stat, leading to the stat drifting away from the true user count.

Fixing this should be as simple as adding that line to increment the stat to [`createAccount`](https://github.com/InternationalScratchWiki/scratch-confirmaccount-v3/blob/c7f995eae78391b4b58ebdbf587e09622ff0adf8/src/database/DatabaseInteractions.php#L233) in [`DatabaseInteractions.php`](https://github.com/InternationalScratchWiki/scratch-confirmaccount-v3/blob/c7f995eae78391b4b58ebdbf587e09622ff0adf8/src/database/DatabaseInteractions.php) (I can create a PR to do this if wanted). To fix the statistic on the wikis themselves, the [`initSiteStats.php`](https://www.mediawiki.org/wiki/Manual:InitSiteStats.php) maintenance script with the `--update` parameter could be used to update the user count.

---

Something kind of interesting: The user count is stopped at `2379`, which is close to the user id for [`User:Abuse filter`](https://en.scratch-wiki.info/w/index.php?title=User:Abuse_filter&action=info) (`2381`). `User:Abuse filter` doesn't seem to have any user creation log entry. However, looking at the creation date of the user created before (`08:12, 30 September 2020 AEST`) and after (`05:42, 1 October 2020 AEST`), in between these two times is `30/09/2020 11:04 AEST`, which is the time jvvg sent an announcement in #announcements about the wiki being down for the MediaWiki 1.35 upgrade. So, this seems to suggest that the user count has been frozen for nearly four years, ever since the MW 1.35 upgrade.

**Comment by jacob-g** [comment]
We created this version of the extension for the 1.35 upgrade, which explains your observations.

This isn't a super high priority issue, but is a pretty simple thing to fix so might as well get it done as time permits.
