### ISSUE TITLE
SQL table name consistency + names in variables

### ISSUE THREAD

**Issue by Ascor8522** [InternationalScratchWiki/scratch-confirmaccount-v3#21]
For more consistency, the `scratch_accountrequest` table should be renamed to `scratch_accountrequest_request` even tho the name sounds redundant, to match `scratch_accountrequest_block` and `scratch_accountrequest_history`.

Also, the table's names and column's names should be put in (global) variables to avoid repetition and to make it easier to maintain.

**Comment by Naleksuh** [comment]
How about _requests and _blocks instead of _ and _block?

**Comment by Kenny2github** [comment]
Done in 968c0be
