### ISSUE TITLE
pre-populated comments from a mediawiki page

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/scratch-confirmaccount-v3#23]
formatting can be like deletereason-dropdown 

there can be generic ones in the default setting, then en will create a mediawiki page based on the needs of its policies

**Comment by Kenny2github** [comment]
See [my user JS](https://en.scratch-wiki.info/wiki/User:Kenny2scratch/acr.js) and [its data file](https://en.scratch-wiki.info/wiki/User:Kenny2scratch/acrmsg.js) for reference on how this could be implemented

**Comment by jacob-g** [comment]
Done.
