### ISSUE TITLE
Rework method of finding verif code

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/scratch-confirmaccount-v3#4]
The current method looks for who most recently commented the code and will deny if it's not the user requesting. This means that if someone comments a code, you can comment the same code to prevent them from being able to request an account. While it won't let you request one either, it does prevent them from requesting and can be used maliciously. So a new method of code finding may be needed.

**Comment by Kenny2github** [comment]
The code should not be guessable - it's essentially a random hash. The chance of someone else randomly commenting the same code is 1 in 1.16×10<sup>77</sup>. The current method provides a much easier way of proofing against leading/trailing underscores and usernames with different case.
On the other side, someone who gives away their code is probably not someone worth accepting anyway.

**Comment by jacob-g** [comment]
The issue in this case is someone might be see the code after it was commented and quickly recomment it. This is unlikely to happen, but possible.

**Comment by Naleksuh** [comment]
Yep basically this. You are "giving away" the code by commenting it. Its
unlikely to happen but does make it out of the control of the person
requesting

**Comment by jacob-g** [comment]
I am going to mark this as won't fix. While this situation is a possibility, it does not cause any potential security issues and is unlikely to happen. If a situation arises where someone does serially troll us by instantly reposting verification comments, we can revisit.
