### ISSUE TITLE
"Actions" label still visible for clients

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/scratch-confirmaccount-v3#43]
Should be hidden

**Comment by jacob-g** [comment]
It would be better to rename rather than hide entirely.

**Comment by Naleksuh** [comment]
I would like some opinions from others on this. This text was visible back when users could still choose multiple actions, but they now cannot, and thus the text serves no purpose. I don't see a reason to rename the text or intentionally make it more vague just to avoid one if statement.

**Comment by jacob-g** [comment]
Hiding it entirely would break the flow of the page though. We could have it display different messages depending on the context, but shouldn't remove it entirely.

**Comment by Naleksuh** [comment]
I don't agree that it would "break the flow of the page". The point of it is that it's where you select actions, but the client cannot select actions. Having Actions then Comment makes no sense when there could be just Comment.

**Comment by jacob-g** [comment]
You completely missed the second part of my previous message: "We could have it display different messages depending on the context, but shouldn't remove it entirely." Maybe "Leave a comment" for the requester and keep as "Actions" for admin. But not having some separation between existing comments and a label to explain what the box is for is ugly and breaks the flow as I said before.

**Comment by Naleksuh** [comment]
But there is already a text saying comment. Why "Leave a comment" then "Comment" again? It makes it redundant which is why I said it should be hidden.

**Comment by jacob-g** [comment]
In this case some redundancy may be good so both the section and field have a label and the page is logically broken up into sections. We could also use something other than "Comment" for the heading.

**Comment by Naleksuh** [comment]
Okay so "Action" becomes "Leave a comment" and "Comment" is removed instead?

**Comment by jacob-g** [comment]
Looking again I do agree that it is a bit confusing that it says "Actions" when there aren't actually any actions. I think "Leave a comment for admin" or something to that effect will be sufficient, while keeping the comment label for the purpose of explicitly labeling the input field.
