### ISSUE TITLE
Remove password from accepted and expired requests

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/scratch-confirmaccount-v3#60]
The removing from expired requests can be done as a job that's triggered randomly or something like that. Removing from accepted requests should be done as soon as the new account is created (*after* creation though in case creation fails).

**Comment by Kenny2github** [comment]
Is there not a job to remove expired requests? Why not lump it in with that?

**Comment by jacob-g** [comment]
Requests live forever now. There is a cooldown of one week (by default, can be customized) after a request is rejected, but the request is saved for later reference.
