### ISSUE TITLE
Add button to copy code to clipboard

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/scratch-confirmaccount-v3#73]
A nice little "copy" icon would appear next to the verification code that would automatically put it in the clipboard and show a tooltip after it's clicked saying "Verification code copied to clipboard!" or something to that effect after being clicked and the code copied.

**Comment by Naleksuh** [comment]
This does introduce a small design problem that I would try to avoid the extension being too interactive or dependent on the client side. Other than that, it does seem like an enhancement
