### ISSUE TITLE
Old requests with "awaiting user" status should expire

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/scratch-confirmaccount-v3#80]
Probably the easiest way to do this would be either to add this to the password clearing job or to create a new job. The job would just find requests with status "awaiting-user" that haven't been commented on in more than some time period (default 30 days maybe?) and for each request set the status to rejected and add an automatically generated comment (the comment could be "from" the admin who first handled the request, since there is guaranteed to be one otherwise the request won't have status awaiting-user).

This would both keep things cleaner from an admin perspective and not force users who abandoned requests to continue with their old one and instead let them request anew.

We kicked the can down the road on this one while originally developing the extension so we could prioritize other things, but it's probably time to start looking into this given that the rest of the extension seems to be working fairly well. It's not an urgent priority, but something to start thinking about (also for reference, the oldest request with status awaiting-user is from October 3, so we still aren't close to the 30 days yet anyway for that request).

**Comment by Ascor8522** [comment]
Hum,

I have a slightly different approach. What if the person is still interested in joining the wiki after making a request and going inactive?

Just like you wouldn't delete the account of an inactive user who hasn't made any commit, you wouldn't want to delete someone's request. Especially if the person is meeting all the requirements.

Can't we just hide/move those requests to a different section/make them less visible and distractive to the admin?

Or even create a new category pf requests. like "active-awaiting-user" and "inactive-awaiting-user".

**Comment by jacob-g** [comment]
In that case, they would just submit a new request, since likely memory of the old request would have faded. However, the case that's probably more likely is they forgot about the request and will be confused when they try to submit a new one and can't because there is already an active request in their name. Also, after 30 days there is a decent change they may have forgotten the password they used.
