### ISSUE TITLE
Hide "copy to clipboard" button for JavaScript-disabled clients

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/scratch-confirmaccount-v3#85]
This will likely be done by adding the button using JavaScript

**Comment by ahmetlii** [comment]
I will do it, thanks for issue.

**Comment by Ascor8522** [comment]
> This will likely be done by adding the button using JavaScript

not necessarly

```html
<html>
<head>
    <noscript><style> .jsonly { display: none } </style></noscript>
</head>

<body>
    <button class="jsonly">Copy to clipboard</button>
</body>
</html>
```

**Comment by jacob-g** [comment]
I like @Ascor8522's solution. That's an elegant way to do it (basically creates something that's the opposite of the `<noscript>` tag) and avoids adding unnecessary complexity to what's already there.

**Comment by Naleksuh** [comment]
Since when is display:none "elegant"?

**Comment by jacob-g** [comment]
I don't know what to say to that other than "no it's not".
