### ISSUE TITLE
Statically load CSS

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/scratch-confirmaccount-v3#87]
This will avoid the issue of CSS sometimes loading *after* the page does and also make the no-JS enhancements work properly.

**Comment by Naleksuh** [comment]
CSS is loaded once the page finishes intentionally as it being loaded when the page is only partially complete may cause issues. However, it is not loaded through JavaScript when JavaScript is not available, so that should not be the cause of the second issue

**Comment by jacob-g** [comment]
Regardless of what information you have, the fact is that the styles are *not* loaded (at least on my browser) if JS is not enabled, and a quick look at the HTML shows no reference to the appropriate resource name other than in the JS ResourceLoader. Also, please read [the MediaWiki documentation](https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader#CSS) before immediately assuming I'm wrong, since it explicitly says "If you have CSS that should be loaded before the page renders (and even when JavaScript is unavailable), queue it via OutputPage::addModuleStyles."

**Comment by Naleksuh** [comment]
My comment was actually in line with what the manual says, interestingly. While loading CSS normally is an option, the standard is to not do so except under specific circumstances due to possible issues.
