### ISSUE TITLE
Prevent empty comments

### ISSUE THREAD

**Issue by Kenny2github** [InternationalScratchWiki/scratch-confirmaccount-v3#96]
Currently users can leave a comment for admin with no content. No harm in this, but probably shouldn't be allowed. It's also likely that admins can leave empty comments as well, which likewise should not be the case.

**Comment by jacob-g** [comment]
This should be done on both the frontend and the backend. For the frontend all we need to do is use the `required` attribute, for the backend reject the form submission if it's empty/whitespace.
